export { default as Upcoming } from './upcoming/Upcoming'
export { default as Vital } from './vital/Vital'
export { default as Logout } from './logout/Logout'
export { default as Tasks } from './tasks/Tasks'
export { default as Dashboard } from './dashboard/Dashboard'
export { default as Completed } from './completed/Completed'